#!/bin/bash
HOST=${HOST:-nyquist}
export PATH=$PATH:${ATOMIX_ROOT_LINUX_STYLE}/r2cmplr
CONFIG_SITE=${ATOMIX_ROOT_LINUX_STYLE}/config.site.debug CC="_cl6x" RANLIB="_ranlib" ${ATOMIX_ROOT_LINUX_STYLE}/configure -build i686-pc-linux-gnu --host ${HOST} ATOMIX_INSTALL_DIR=${ATOMIX_ROOT}/build $@
