#!/usr/bin/env python

import sys
import struct

SAMP_MAX = 32767.0

#var_len = 8
#var_str = "!d"
var_len = 4
var_str = "f"

var_max = None

filename = None
if (len(sys.argv) <= 1):
	print "Usage: %s <filename>                                 \
	Behavior: input complex double samples and output int samples" % sys.argv[0]
	sys.exit(1)
else:
	filename = sys.argv[1]

f = open(filename, 'r')
d = f.read()

arr = []
for i in range(0, len(d), var_len*2):
	var1 = struct.unpack(var_str, d[i:i+var_len])[0]
	var2 = struct.unpack(var_str, d[i+var_len:i+(var_len*2)])[0]

	# find max for normalization
	if (var_max == None):
		var_max = var1	
	if (abs(var1) > var_max):
		var_max = var1
	if (abs(var2) > var_max):
		var_max = var2

	arr.append((var1, var2))

# print normalized samples 
for i in range(0,len(arr)):
	(var1, var2) = arr[i]

	out_str = ""
	out_str += "% 10d, % 10d" % ((var1/var_max)*SAMP_MAX, (var2/var_max)*SAMP_MAX)

	if (i < (len(arr)-1)):
		out_str += ","

	out_str += "\n"
	sys.stdout.write(out_str)
