#!/bin/bash

if [[ $# -lt 1 || $1 = "-h" ]]; then
  echo "Usage: $0 <id>"
  exit
fi

WIFIBB_TRACES=~/Projects/wifibb-traces
REFDIR=${WIFIBB_TRACES}/data
REFDIR_B=${WIFIBB_TRACES}/bdata
TRACEDIR=.

CONFSTR=rate6.snrInf.nmsgs1.msglen200.scale1.41.

if [[ $1 = 0 ]]; then
  d=`pwd`
  cd $TRACEDIR
  parsedat -a ../atom_profiling_table.txt -d ../atom_db.txt
  cd $d
fi

if [[ $1 = 1 ]]; then
	for i in `seq 0 69`;
	do
		parsedat -s $i -S $i -t CPLXDBL -r $REFDIR_B/${CONFSTR}allMappedSymbols.mdat -b 48 -T CPLX16 bpskMapper.bho0.outSampleBuf.ORILIB_t_Cplx16Buf48.dat
	done
fi

if [[ $1 = 2 ]]; then
	for i in `seq 0 69`;
	do
		parsedat -s $i -S $i -t CPLXDBL -r $REFDIR_B/${CONFSTR}allOfdmMod.mdat -b 80 -T CPLX16 $TRACEDIR/ofdmMod.bho0.*.dat 
	done
fi

if [[ $1 = 3 ]]; then
	echo "Warning: Doesn't check the PLCP header, but I checked it manually and it's fine"
	for i in `seq 0 68`;
	do
		parsedat -s $i -S $i -t DBL -r $REFDIR_B/${CONFSTR}dataConvBits.mdat -b 48 -T UINT8 $TRACEDIR/puncturer.bho0.outByteBuf.ORILIB_t_ByteBuf48.dat
	done
fi

if [[ $1 = 4 ]]; then
	for i in `seq 0 8 551`;
	do
		parsedat -v --skip-ref-bytes $(($i*8)) --skip-test-bytes $i -t DBL -r $REFDIR_B/${CONFSTR}dataPreConvBits.mdat -b 3 -T UINT8 $TRACEDIR/scrambler.bho0.outBuf.ORILIB_t_BitBucket24.dat
	done
fi
