#!/usr/bin/env python

import sys, pickle

def preproc(tf):
  f = open(tf, 'r')
  sls = [line.split()[1:] for line in f.readlines()]
  f.close()

  if len(sls) == 0:
    print 'No data in trace file'
    sys.exit(1)


  if len(sls[0]) == 6:
    dd = [(dnum,idv,ts) for (ig1, dnum, ig2, idv, ig3, ts) in sls]
  elif len(sls[0]) == 5:
    dd = [(dnum,idv,ts) for (dnum, ig2, idv, ig3, ts) in sls]
  else:
    print 'bad format'
    sys.exit(1)

  dd0 = [(idv,float(ts)) for (dnum,idv,ts) in dd if dnum == '0']
  dd1 = [(idv,float(ts)) for (dnum,idv,ts) in dd if dnum == '1']
  dd2 = [(idv,float(ts)) for (dnum,idv,ts) in dd if dnum == '2']
  dd3 = [(idv,float(ts)) for (dnum,idv,ts) in dd if dnum == '3']

  return (dd0, dd1, dd2, dd3)


def main():
  print 'Parsing for tsconf=st'

  tracefile = sys.argv[1]
  pdumpfile = sys.argv[2]
  tdumpfile = sys.argv[3]
  print 'Preprocessing', tracefile

  ddtup = preproc(tracefile)
  #print ddtup

  pickle.dump(ddtup, open(pdumpfile, "wb"))
  f = open(tdumpfile, "w")
  f.write(str(ddtup))
  f.close()

  print 'Written', pdumpfile
  print 'Written', tdumpfile


if __name__ == "__main__":
  main()
